In [1]:
import pandas as pd

In [2]:
vine_df = pd.read_csv("vine_table.csv")
vine_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,R3DT59XH7HXR9K,5.0,0.0,0.0,N,Y
1,R1LFS11BNASSU8,5.0,0.0,1.0,N,Y
2,R296RT05AG0AF6,5.0,0.0,0.0,N,Y
3,R3V37XDZ7ZCI3L,5.0,0.0,1.0,N,Y
4,R14GU232NQFYX2,5.0,0.0,0.0,N,Y
...,...,...,...,...,...,...
4880461,R22DLC2P26MUMR,4.0,30.0,41.0,N,N
4880462,R1N6KLTENLQOMT,5.0,84.0,92.0,N,N
4880463,R10TW4QXDV8KJC,4.0,55.0,60.0,N,N
4880464,R41RL2U1FSQ4V,4.0,30.0,42.0,N,N
4880465,R1NHMPKSJG2E37,5.0,5.0,5.0,N,N

In [13]:
# New dataframe where total_votes >= 20
votes_df = vine_df[vine_df["total_votes"]>= 20]
votes_df.head(30)

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
18,R28RB82UG4RDD5,5.0,20.0,20.0,N,Y
233,R3FB6BERWPEIJP,4.0,40.0,43.0,N,Y
615,R1D4Z38STRDQXK,5.0,53.0,56.0,N,Y
1065,R1XMWJZICINIFX,3.0,20.0,21.0,N,Y
1105,R20QKY1GABXFLM,1.0,272.0,297.0,N,Y
1434,R3GZ7CK2O1PPG0,2.0,10.0,30.0,N,Y
1504,R328FA1E6FY3F5,5.0,17.0,20.0,N,N
1538,R3DH22AA5WGLLS,5.0,30.0,30.0,N,N
1713,R1E0E5EFZSLJCS,1.0,66.0,80.0,N,Y
1999,R1TXZQWEHYWEWN,2.0,48.0,51.0,N,Y
2003,RQQAI8YL3UCY2,5.0,23.0,25.0,N,Y
2159,R3PZNAQREFUNJ7,4.0,28.0,35.0,N,Y
2407,R1ZUNUSUEA5D0T,2.0,17.0,20.0,N,Y
2508,R3SHJSHTY8AXKR,5.0,69.0,72.0,N,Y
2862,R2QM1JXA2XI7XA,3.0,61.0,68.0,N,Y
3528,R1SVJ6XDBCQNSN,3.0,29.0,30.0,N,Y
3720,R1IEABNX71GK3B,1.0,54.0,58.0,N,N
3832,R16QL1GNQVT4G9,5.0,117.0,119.0,N,Y
3953,R1MV4YDD6O5UME,5.0,30.0,32.0,N,N
3960,R3A8EHXA0JX7WV,5.0,18.0,24.0,N,N
4272,R2M7TEVV9YSLTR,5.0,94.0,96.0,N,Y
4789,R3BAP1S0295WA4,5.0,248.0,259.0,N,N
5966,RM96N21990RSS,1.0,19.0,20.0,N,Y
6117,RUDQ2KHBY4I5O,5.0,66.0,69.0,N,Y
6627,R6TSTUAOAJI5J,2.0,11.0,33.0,N,Y
6631,R3HUF34U7WSS4S,1.0,12.0,26.0,N,N
6821,R241UWB9DHBSK0,5.0,18.0,28.0,N,Y
6868,RO36WR5NPQNUU,1.0,45.0,47.0,N,Y
6886,RU1J46UT6V0JD,5.0,25.0,29.0,N,N
7248,R3UPJ5Y3F10891,5.0,45.0,49.0,N,Y

In [7]:
votes_df.dtypes

review_id             object
star_rating          float64
helpful_votes        float64
total_votes          float64
vine                  object
verified_purchase     object
dtype: object

In [14]:
# New dataframe where number of helpful_votes / total_votes is greater or equal to 50%
new_votes_df = votes_df[votes_df["helpful_votes"] / votes_df["total_votes"] >= 0.5]
new_votes_df.head(30)

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
18,R28RB82UG4RDD5,5.0,20.0,20.0,N,Y
233,R3FB6BERWPEIJP,4.0,40.0,43.0,N,Y
615,R1D4Z38STRDQXK,5.0,53.0,56.0,N,Y
1065,R1XMWJZICINIFX,3.0,20.0,21.0,N,Y
1105,R20QKY1GABXFLM,1.0,272.0,297.0,N,Y
1504,R328FA1E6FY3F5,5.0,17.0,20.0,N,N
1538,R3DH22AA5WGLLS,5.0,30.0,30.0,N,N
1713,R1E0E5EFZSLJCS,1.0,66.0,80.0,N,Y
1999,R1TXZQWEHYWEWN,2.0,48.0,51.0,N,Y
2003,RQQAI8YL3UCY2,5.0,23.0,25.0,N,Y
2159,R3PZNAQREFUNJ7,4.0,28.0,35.0,N,Y
2407,R1ZUNUSUEA5D0T,2.0,17.0,20.0,N,Y
2508,R3SHJSHTY8AXKR,5.0,69.0,72.0,N,Y
2862,R2QM1JXA2XI7XA,3.0,61.0,68.0,N,Y
3528,R1SVJ6XDBCQNSN,3.0,29.0,30.0,N,Y
3720,R1IEABNX71GK3B,1.0,54.0,58.0,N,N
3832,R16QL1GNQVT4G9,5.0,117.0,119.0,N,Y
3953,R1MV4YDD6O5UME,5.0,30.0,32.0,N,N
3960,R3A8EHXA0JX7WV,5.0,18.0,24.0,N,N
4272,R2M7TEVV9YSLTR,5.0,94.0,96.0,N,Y
4789,R3BAP1S0295WA4,5.0,248.0,259.0,N,N
5966,RM96N21990RSS,1.0,19.0,20.0,N,Y
6117,RUDQ2KHBY4I5O,5.0,66.0,69.0,N,Y
6821,R241UWB9DHBSK0,5.0,18.0,28.0,N,Y
6868,RO36WR5NPQNUU,1.0,45.0,47.0,N,Y
6886,RU1J46UT6V0JD,5.0,25.0,29.0,N,N
7248,R3UPJ5Y3F10891,5.0,45.0,49.0,N,Y
7449,R2AEYWMQPOHVVH,2.0,21.0,23.0,N,Y
7462,RUOS97BPV7QDT,5.0,34.0,37.0,N,Y
7695,R2C4FJ9LFIWF3V,1.0,21.0,23.0,N,Y

In [84]:
paid_review = new_votes_df[new_votes_df["vine"]== "Y"]
paid_review

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
13470,R1Z71RW4J9IK93,5.0,20.0,22.0,Y,N
18140,R3FVB5QI11KI9Q,4.0,192.0,200.0,Y,N
20156,R2G027YBMVXV6Y,5.0,39.0,48.0,Y,N
26393,R1QGBAN7BMGWRR,5.0,121.0,129.0,Y,N
28369,R2NH2AU7XL9ZDZ,3.0,18.0,20.0,Y,N
...,...,...,...,...,...,...
4662711,R2D7ZSUZ5LME8B,3.0,37.0,48.0,Y,N
4662751,RPNMEK7LNID1S,4.0,129.0,136.0,Y,N
4662752,R1K9IAOAHMQFFK,5.0,80.0,85.0,Y,N
4663306,R3JJWL3N25MFSE,5.0,317.0,329.0,Y,N
4663754,R1T3LTPPABEWPK,5.0,59.0,63.0,Y,N

In [83]:
unpaid_review = new_votes_df[new_votes_df["vine"]== "N"]
unpaid_review

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
18,R28RB82UG4RDD5,5.0,20.0,20.0,N,Y
233,R3FB6BERWPEIJP,4.0,40.0,43.0,N,Y
615,R1D4Z38STRDQXK,5.0,53.0,56.0,N,Y
1065,R1XMWJZICINIFX,3.0,20.0,21.0,N,Y
1105,R20QKY1GABXFLM,1.0,272.0,297.0,N,Y
...,...,...,...,...,...,...
4880460,R2SLX958DGMAIG,4.0,21.0,21.0,N,Y
4880461,R22DLC2P26MUMR,4.0,30.0,41.0,N,N
4880462,R1N6KLTENLQOMT,5.0,84.0,92.0,N,N
4880463,R10TW4QXDV8KJC,4.0,55.0,60.0,N,N
4880464,R41RL2U1FSQ4V,4.0,30.0,42.0,N,N

In [27]:
# Count total number of ratings for paid reviews
total_reviews = paid_review["review_id"].count()
total_reviews

1207

In [28]:
#Count number of ratings with 5 stars for paid reviews
five_stars_df = paid_review[paid_review["star_rating"] == 5.0]
five_stars = five_stars_df["star_rating"].count()
five_stars

509

In [29]:
# Calculate percentage of 5-star reviews for paid reviews 
fivestart_percent = five_stars / total_reviews * 100
fivestart_percent

42.17067108533554

In [80]:
# Create a function to find the total number of reviews, total number of 5 star reviews, 
# and percentage of 5 star reviews for each review type
def reviews(review_type):
    
    total = review_type["review_id"].count()
    
    five_stars_df = review_type[review_type["star_rating"] == 5.0]
    five_stars = five_stars_df["star_rating"].count()
    
    fivestar_percent = five_stars / total * 100
    
    return print (f"The total number of reviews is {total}.\nThe total number of 5 star reviews is {five_stars}.\nThe percentage of 5 star reviews is {fivestar_percent:.2f}%.")

In [81]:
reviews(paid_review)

The total number of reviews is 1207.
The total number of 5 star reviews is 509.
The percentage of 5 star reviews is 42.17%.

In [82]:
reviews(unpaid_review)

The total number of reviews is 97839.
The total number of 5 star reviews is 45858.
The percentage of 5 star reviews is 46.87%.